### ISSUE TITLE
OU Privilege Mapper cannot be edited

### ISSUE THREAD

**Issue by swamipurnamsha** [Blazam-App/BLAZAM#292] opened 2024-04-05 11:19 UTC
The OU privilege mapper cannot be edited.

We are running the Blazam App as a service on **Blazam version: 0.9.0.2024.03.30.1856**

When accessing Blazam Configure->Permissions->Mappings->OU Privilege Mapper, we've encountered an issue where the checkbox for providing mappings to delegates doesn't become selected, preventing us from saving new mappings. This problem persists in the demo website, as illustrated in the attached[ .GIF](https://we.tl/t-mRiyiV8rqo)

This issue was not there in the earlier releases.

OS: Windows Server 2022
Browser: Google Chrome
Version: 123.0.6312.105

**Comment by jacobsen9026** [comment] 2024-04-05 20:44
Hello,

Yes, two issues were recently discovered from recent updates, this, and the
breaking of setting parent templates for user creation templates. I am
leaving on vacation for 5 days, I was hoping to get a patch out this week,
but it will have to wait until I return.

I apologize for any inconvenience this may cause, and appreciate the
support you provide to Blazam, better every day thanks to people like you.

**Comment by jacobsen9026** [comment] 2024-04-05 22:52
Caused by commit id c415969a4a4b2b5bfdefc23302ca35f0d860d36e

**Comment by jacobsen9026** [comment] 2024-04-11 22:46
> Caused by commit id [c415969](https://github.com/Blazam-App/BLAZAM/commit/c415969a4a4b2b5bfdefc23302ca35f0d860d36e)

I was wrong on that, a year old commit, but was the most likely candidate in my code for the cause.

Alas, the web presentation framework MudBlazor is to blame. 

I have reverted back to a version before the flaw was introduced.

Will be included in next update. Can't give an ETA yet.

23c1be31b8e21ab2dc1c24bbc58b9ebb81a3f587

**Closed as completed by jacobsen9026** 2024-04-11 22:46 UTC

**Comment by jacobsen9026** [comment] 2024-04-13 21:10
@swamipurnamsha v0.9.1 is about to be released

**Comment by swamipurnamsha** [comment] 2024-04-14 07:05
@jacobsen9026 We eagerly await the release. We have moved to production with the current code, Considering the security aspects where the delegation of blazam admins currently only allows them as a Blazam super admin, we are in a bit of a risk with trusting delegated members outside of IT with this privilege. Hope it releases soon. Thanks

**Comment by jacobsen9026** [comment] 2024-04-14 16:35
@swamipurnamsha  Delegating administrative permissions has been considered. With your desire for them, I may be motivated enough to implement. That and expanding Computer permissions due to the all or nothing approach with the real-time tools.

Would you be willing to open a new issue with what you would like to be able to delegate to "power-users"/"non-super admins"?

It will give my roadmap some direction... I'm not exactly sure what else to add besides a proper notification system to email and in-app before v1.0

**Comment by swamipurnamsha** [comment] 2024-04-15 17:13
hi Chris definitely we would like to have blazam for an AD delegation for non IT members. Sharing the use case below:


Use Case 1:
The tasks we are currently doing in AD on daily basis:
Creating users, Enabling/Disabling users, Resetting passwords, Assigning/Unassigning users to groups, Mapping computers to users.
All these tasks are being done by a couple of people(lets call this group: helpdesk) and they do these taassks by accessing AD.

In order to make sure that AD data is not modified unintentionally by helpdesk, we need to stop anyone from accessing Active directory directly (except a couple of admins).

Blazam can help in this case where we need to provide these group of people a non-superuser access through Blazam and the above mentioned administrative tasks can be performed through Blazam. But currently due to a bug in Blazam, helpdesk members are not able to perform these tasks (but a blazam super user can perform just fine)

Use case 2: 
We have different departments in our organization which are represented by different OUs in AD.
We want to delegate these administrative tasks to the respective departments.
In order for that to happen, we need a couple of persons from each OU/department(lets call these couple of people: dept_spoc group) to be given a non-superuser access to Blazam. Effectively, there will be 1 dept spoc group in each departmet/OU.
And they can login to Blazam and perform these tasks for members of their own departments.

The important thing here is that they should not be able to perform these actions on any OU/department, other than their own.

For this we need to set access permissions for each dept_spoc group in such a way that this group can not modify any property outside their own department/OU.
(Right now it is not possible in Blazam).
