### ISSUE TITLE
System.ArgumentNullException when creating new template

### ISSUE THREAD

**Issue by Tacoo99** [Blazam-App/BLAZAM#616] opened 2024-10-30 10:35 UTC
**Describe the bug**
Bug appears when i want to create new template.

**Steps to reproduce**
Just install and configure everything using web installer, IIS and MariaDB

**Screenshots**
![image](https://github.com/user-attachments/assets/29b4ae43-1259-4dd3-99c4-e0d7f0f71e95)

**Environment (please complete the following information):**
- Blazam Version: Latest(v1.0.7.2024.10.30.0007)
- Running under IIS(same problem with Service)

**Comment by jacobsen9026** [comment] 2024-10-30 22:19
This one is a new feature teething situation. The new variable substitution simulator did not account for empty formulas. 

However, this bug has existed from before the simulator was created. It was not as apparent an issue previously because it would only have occurred during user creation and by then a formula was usually provided which would have avoided the error.

The fix for this is also in the Dev branch for testing.

ETA on both is <18 hours

**Comment by jacobsen9026** [comment] 2024-10-30 22:31
FYI, I love your contributions, but I feel guilty.

To save yourself a headache, I would say you're going a little bit overboard on the testing of bugs. It's usually not necessary to create fresh installs or test against service and IIS hosting types on your end (unless you need the sanity check). Simply knowing what ones you're using is sufficient, and I'm almost always manually testing against a "basically fresh" install, and can spin up a fresh instance in a couple of minutes if I need it. That also goes for anything that would be database type or hosting type specific.

If I can't reproduce the issue, that's when I'll ask for you to try some of the above and beyond things you've been doing.

Again, I can't express the appreciation I have for your bug reports, and I'd love to give you the opportunity to transition to feature requests.

Cheers.

**Comment by Tacoo99** [comment] 2024-10-30 22:40
Don't worry and don't feel guilty, I did a fresh install, because I want to set up all on IIS, not service and it took me about 5 minutes thanks to your web installer.
I took the opportunity to confirm that the same thing occurs on a clean installation.

I'm appreciative of you and other contributors/devs for developing such nice software, especially open source.

**Comment by jacobsen9026** [comment] 2024-10-31 01:21
Very little changes in the latest release. Mostly addressing your issues.

**Closed as completed by jacobsen9026** 2024-10-31 01:21 UTC
Labels: bug
